use_frameworks!

platform :ios, '10.0'

target 'GMModulizationDemo_Example' do
  pod 'GMModulizationDemo', :path => '../'

  target 'GMModulizationDemo_Tests' do
    inherit! :search_paths

    
  end
end
